name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v4

      # 2. Cache pip deps for speed
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 3. Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. (Optional) Lint your code
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src

      # 6. Run the training script
      - name: Train model
        run: python src/train.py

      # 7. Run the evaluation script
      - name: Evaluate model
        run: python src/evaluate.py

      # 8. Upload artifacts (models & metrics)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: artifacts/
